import MainSlider from "@/components/MainSlider/MainSlider";
import Head from "next/head";
import Image from "next/image";

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Pizza Denis</title>
        <meta name="description" content="Venez découvrir nos pizzas artisanales et savoureuses préparées avec amour au feu de bois avec des ingrédients frais et de qualité pour vous offrir une expérience gustative unique ! Située à quelques kilomètres de Perpignan, Barcarès et Canet en Roussillon, notre pizzeria est facilement accessible pour les locaux et les visiteurs de passage. Commandez et emportez votre pizza pour déguster chez vous, sur la plage ou en vacances. Ne manquez pas nos pizzas gourmandes, nos pizzas aux fruits de mer ou nos végétariennes. Jetez un oeil au menu et contactez-nous dès maintenant pour passer commande !" />
      </Head>
      <main>
        <MainSlider />
        <p>
          Dolore ullamco quis ex laborum fugiat laboris tempor nisi culpa labore ipsum nulla. Sunt esse id laboris aliquip est aliquip ad reprehenderit. Proident sunt irure culpa est. Fugiat do tempor labore elit quis id cupidatat incididunt in. Occaecat aute ex Lorem velit non ullamco cupidatat nulla. Tempor veniam et mollit adipisicing ad voluptate. Ex dolor magna consequat Lorem qui dolor enim Lorem nulla aliqua. Est do laborum commodo voluptate pariatur mollit dolore ad. Velit quis sunt aute enim id quis qui mollit aliquip laboris. Veniam enim aute consectetur dolore reprehenderit dolor adipisicing nisi laboris elit sint non ex aliquip. Occaecat voluptate ipsum ad aute quis eiusmod ut tempor dolore exercitation. Consequat excepteur sint consequat adipisicing elit exercitation excepteur commodo aliquip. Nulla nulla cupidatat velit ex deserunt minim ullamco aliqua deserunt deserunt commodo anim ullamco magna. Dolore amet ad laborum laborum in. Veniam tempor do fugiat id est dolore ex labore consequat dolore. Consectetur ullamco ut aliqua eu ullamco incididunt in elit minim anim sunt. Veniam dolor et est laborum Lorem consectetur fugiat consequat culpa magna est esse enim est. Aliquip nostrud est aliquip fugiat do dolor et velit esse ipsum. Do occaecat veniam deserunt reprehenderit. Velit deserunt eu reprehenderit sint velit veniam deserunt laborum Lorem. Voluptate esse labore sit in ea commodo consectetur cupidatat dolor officia officia consectetur officia dolore. Laboris sit esse laborum commodo minim laborum reprehenderit. Deserunt incididunt Lorem nulla enim eiusmod anim voluptate. In anim fugiat sunt Lorem in ea do excepteur ad enim aliquip deserunt. Sunt irure eu veniam ex ipsum deserunt excepteur id excepteur qui cillum ad. Magna sit ut ipsum dolore veniam consequat proident tempor voluptate esse ullamco velit minim excepteur. Aliquip fugiat id exercitation aliquip elit. Amet irure eu voluptate laboris reprehenderit qui eiusmod sit ullamco mollit cillum
          nulla sit ea. Do ex consequat aute eu qui anim dolor. Non ullamco sit aute minim ut duis tempor Lorem exercitation fugiat. Irure mollit ea esse eu ea culpa dolor reprehenderit in exercitation minim in. Ullamco nulla sint amet ut nostrud ex enim adipisicing sit consectetur consectetur veniam ad deserunt. Culpa ea fugiat pariatur ex nulla dolor fugiat mollit amet anim nostrud qui incididunt eu. Aute magna ea adipisicing pariatur irure consequat aliqua. Ea est esse culpa nulla adipisicing veniam adipisicing sit eu. Officia magna cupidatat aute dolore. Aliqua Lorem elit nulla ipsum labore velit ea veniam incididunt. Laborum cupidatat deserunt reprehenderit excepteur consectetur eiusmod adipisicing sint amet Lorem esse minim aute deserunt. Voluptate do aute ad magna. Laboris ullamco laboris tempor ut mollit ullamco pariatur officia esse eu. Non consequat et non dolore tempor irure Lorem. Officia aute et non consequat incididunt anim labore adipisicing. Sint ullamco laborum adipisicing esse. Nulla minim ad magna irure anim amet quis id. Enim laborum aute ex excepteur laboris commodo id proident labore nisi id. Deserunt consequat occaecat mollit veniam nisi laboris ut elit commodo id nisi ex occaecat. Amet aute reprehenderit non nulla in id dolor. Mollit non dolore consectetur excepteur incididunt tempor eiusmod nisi enim do consectetur. Reprehenderit proident enim ex tempor. Amet proident cupidatat adipisicing laborum magna veniam sunt mollit sint amet consectetur. Nulla in qui consequat est. Velit fugiat culpa ea commodo. Laborum commodo Lorem pariatur aute incididunt ea. Elit ea non occaecat esse do nulla adipisicing ipsum. Veniam elit aute aliquip commodo voluptate est.
        </p>
      </main>
    </>
  );
}
